"""empty message

Revision ID: 305098069601
Revises: 6b4c50c71d3d
Create Date: 2022-07-25 18:33:05.211302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305098069601'
down_revision = '6b4c50c71d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
